apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    app.kubernetes.io/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - image: okteto/python-fastapi
        name: fastapi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: okteto/python-fastapi
        name: worker
        command:
        - celery    
        - worker
        - --app=code.worker.app
        - --concurrency=2
        - --loglevel=INFO
---

apiVersion: v1
kind: Service
metadata:
  name: fastapi
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "fastapi"
    port: 8080
  selector:
    app: fastapi